### PR TITLE
Fix code indentation and header levels on contributing page.

### PR DESCRIPTION
**Pull request by kjellander-unity**
_sigh_ the indented lists with code are hard. 8 spaces required it seems (http://meta.stackexchange.com/questions/3792/how-to-nest-code-within-a-list-using-markdown)

### CODE REVIEW

**Comment by kjellander-unity** [comment]
Fixed header levels as well.

**Comment by kjellander-unity** [comment]
I'll push this now since the current (accidentally pushed page) looks bad.

**Comment by louquillio** [comment]
@hkjellander, try backtick or tilde delimiters for code blocks -- especially for code blocks in list items, where the four-space indentation method becomes inelegant, and often brittle. Gist:

https://gist.github.com/louquillio/2e526addf04ac753723139e021663597

**Comment by kjellander-unity** [comment]
Yeah, but I actually had it aligned like that in the first commit, but I think the two levels of list items messed things up. I removed the second level in #71. I'll try to pay more attention to issues like this in the future. 
@louquillio, do you know from the top of your head how to get the style we use for webrtc.org into the Sublime Markdown Preview plugin? It currently gives me two styles to choose between (github/markdown) but neither was looking exactly as when pushed to webrtc.org. 
The same problem exists when clicking the "View" button in the GitHub PR user interface - it's not using the same style.

**Comment by louquillio** [comment]
@hkjellander, I use Sublime too, but don't use a previewing plugin. Still, I see that gh-pages now exclusively uses Jekyll 3.0 and therefore kramdown for Markdown transforms. A previewer based on kramdown should function identically.

https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

Unfortunately there are many previewer plugins for Sublime and it's not obvious to me which ones use pure kramdown. Likely this will improve now that GitHub has settled on kramdown, but that's a recent development.

**Pull request merged**
