### PR TITLE
Update gem deps

### PR DESCRIPTION
**Pull request by KaptenJansson**
Github complains about a vulnerability in RedCloth 4.2.9.

### CODE REVIEW

**Comment by MirkoBonadei** [comment]
Were we using RedCloth? Looking at the diff we are just dropping it but why was it there before?

**Comment by KaptenJansson** [comment]
Not sure, I just did a gem update and it seems like whatever was using it does not need it anymore.

**Comment by x1ddos** [comment]
Hey @KaptenJansson did you try building the website locally and see if it produces the same results visually?

**Comment by x1ddos** [comment]
@MirkoBonadei RedCloth was a dependency of github-pages, I believe.

**Comment by x1ddos** [comment]
> Hey @KaptenJansson did you try building the website locally and see if it produces the same results visually?

Never mind. I've just tried and it seems to work well.

**Review by x1ddos — APPROVED** [review]

**Comment by MirkoBonadei** [comment]
Thanks Alex!

**Comment by KaptenJansson** [comment]
Yeah thanks a lot @x1ddos !

**Pull request merged**
