### PR TITLE
added picshare.jooink.com in the Applications/getUserMedia section

### PR DESCRIPTION
**Pull request by abmancini**
I've added a link to a possibly interesting application in the section Applications/getUserMedia.
Thanks.

### CODE REVIEW

**Comment by KaptenJansson** [comment]
Potentially cool demo although it did not work for me, the little 3D dinosaur was all over the place. Could you also provide some info about the company and what components the demo is built upon?

**Comment by abmancini** [comment]
Thanks. 
Can you share a picture of the background ? 
The marker-based augmented reality matching algorithm is subject to some false positives sometime (due to overly complex background or strange lighting) but usually as soon as you show a marker (this is the default one http://www.jooink.com/experiments/NyARMarkers/42.pdf ) the matching is good and fast. 

The company (jooink.com) is just me and my teammate Francesca (co-author of the demo). We work as 'web' developers and teachers (mostly java, javascript and sometime C and C++). 

Picshare itself has been described in some conferences and blogs: 
https://www.toptal.com/augmented-reality/augmented-reality-in-browser-gwt
https://docs.google.com/presentation/d/1pfSQkvSn_qttb4fjBWcm3RtubXRLKY9kB8jEK7YJLSE/edit#slide=id.p

Roughly speaking picshare is a porting of 'NyArToolkit'  for the web and most of the code has been published on github:
https://github.com/abmancini/gwt-nyartoolkit
https://github.com/abmancini/gwt-webgl
https://github.com/abmancini/getusermedia-jsinterop

The java part is compiled to javascript via GWT whereas the video stream is accessed via getUserMedia and the 3D Models are drawn via WebGL.

If you want we are of course pleased to share any detail.

**Comment by KaptenJansson** [comment]
Aha I see. Perhaps you could make the demo more clear for the user? I had no idea that I should print out markers or display it on a phone and hold it in front of the camera.

Thanks for the detailed info about your page.

cc @samdutton @juberti WDYT?

**Comment by abmancini** [comment]
Well, that's true ! we will certainly  try to give instructions the the users. Thanks.

**Comment by samdutton** [comment]
I've tried this out — WFM :). 

I've seen quite a lot of 'augmented' apps like this, but this is a nice demo.

Haven't had time to take a look at the code.

**Comment by KaptenJansson** [comment]
LGTM, just needs to be rebased with gh-pages.

**Pull request merged**
