### PR TITLE
Add a note about shipping fat ios frameworks

### PR DESCRIPTION
**Pull request by kthelgason**
This is in response to [this](https://groups.google.com/forum/#!topic/discuss-webrtc/wu7N0jCb8Po) issue raised on webrtc-discuss.

### CODE REVIEW

**Comment by kthelgason** [comment]
cc @hkjellander

**Review by kjellander-unity — APPROVED** [review]
Tip: you can "assign" the issue to me instead of CCing...

**Comment by kthelgason** [comment]
I actually can't, I think I need to be a "collaborator" for that, not just "contributor"

**Comment by KaptenJansson** [comment]
collaborator is for people outside the team while contributor is for people inside the team. I think you should have access.

**Comment by kthelgason** [comment]
@KaptenJansson: Ah, ok. Yes I have access now, was added to the team.

**Pull request merged**
