### PR TITLE
Fix for incorrect upload CLs command in contributing page

### PR DESCRIPTION
**Pull request by jaoo**
#### What is this PR doing?

Adding a fix for incorrect upload CLs command in contributing page.

### CODE REVIEW

**Review by MirkoBonadei — APPROVED** [review]

**Comment by MirkoBonadei** [comment]
Thanks!

**Comment by jaoo** [comment]
@MirkoBonadei Thanks for approving this PR. I guess once Travis finishes you will merge the PR (assuming Travis reports everything is alright). What happen if the Travis CI build fails?, who is is charge of re running Travis? Thanks.

**Comment by MirkoBonadei** [comment]
I can take care of that. For example Travis reported a problem with a broken link but I will merge your CL and fix that later.

**Comment by jaoo** [comment]
@MirkoBonadei Cool, thanks!

**Pull request merged**
