### PR TITLE
Added Getting Started Guide

### PR DESCRIPTION
**Pull request by samdutton**
@louquillio @blum @juberti 

Made a start on this based on content from [g.co/webrtc](https://g.co/webrtc).

Please feel free to suggest additions/deletions!

View live at [samdutton.github.io/webrtc-org/start](https://samdutton.github.io/webrtc-org/start/).

### CODE REVIEW

**Comment by samdutton** [comment]
Hmm... This seems to have gone live. Not sure how.

**Comment by x1ddos** [comment]
I think it might be my fault. I recently change CI configuration and didn't realize this would push this PR too. Will fix it ASAP and roll back webrtc.org site to the previous state.

**Comment by x1ddos** [comment]
Done. @samdutton could you rebase this PR to webrtc:gh-pages? That way CI will pick up correct config for the PR.

**Comment by samdutton** [comment]
@crhym3 OK — never done that before :). 

Do you mean like the instructions here: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by KaptenJansson** [comment]
@samdutton Awesome! Thanks for doing this, this will be perfect to point people too!

**Comment by x1ddos** [comment]
@samdutton yeah, that seems like a complete documentation on rebasing with github but to sum-up for this specific case, here's what I think I'd do:

``` sh
# from my local copy of the forked repo samdutton:gh-pages:
# 1. add webrtc-org repo remote as "upstream" (one-off step)
$ git remote add upstream git@github.com:webrtc/webrtc-org
# 2. fetch from upstream/gh-pages, fast-forward merge with my origin/gh-pages
# and place commits of this PR on top of that
$ git pull --rebase upstream gh-pages
# 3. push rebased commits to samdutton:gh-pages and thus overwriting it,
# which will also update this PR automatically
$ git push -f origin gh-pages
```

If anything goes wrong, you can always do `git reset --hard origin/gh-pages` to get to the original state.

I'll be happy to help you do it on Monday if you want.

**Comment by samdutton** [comment]
> could you rebase this PR to webrtc:gh-pages? That way CI will pick up correct config for the PR.

May need some help with this on Monday. Tried rebasing but ran into problems...

**Comment by samdutton** [comment]
No objections, so merging now.

**Comment by samdutton** [comment]
I've merged this.

Tweeted here https://twitter.com/sw12/status/706859359079407617.

**Pull request merged**
