### PR TITLE
bugs: move content around

### PR DESCRIPTION
**Pull request by fippo**
so that it makes more sense

### CODE REVIEW

**Comment by fippo** [comment]
@MirkoBonadei @alvestrand this version is more up-to-date than the one on the "official" website. Lets merge this and then put it into the native repo docs?

**Comment by MirkoBonadei** [comment]
There is https://webrtc.org/support/bug-reporting on the webrtc.org website. I think it is fine to avoid to add this into to docs/ and avoid duplication.

**Comment by fippo** [comment]
the version on the "official" website is based on an outdated version of the one in this repository, missing content like 12710e0ed1b43c1e37782d65f9ab121fcd7b35a1. And there is a change process that works and allows contributions for the repo (and not for the website)

**Comment by MirkoBonadei** [comment]
Ok, I think the best solution is to move this to the docs/ folder of the WebRTC repo and link that on the main website in order to have only one place where we have this info. Can you file a CL on docs/? When that lands I can update the website.

Let's wait for that before landing this.

**Comment by fippo** [comment]
can we land this first so we have a stable commit hash to say "copy of ... at ..." in the CL? ;-)

**Review by MirkoBonadei — APPROVED** [review]

**Comment by MirkoBonadei** [comment]
Ok, let's proceed with this one as well.

**Comment by fippo** [comment]
I ended up having to cherry-pick so a commit hash makes no sense anyway. CL will be up shortly. Oh and I found more...

**Pull request closed without merging**
