### PR TITLE
Update jQuery to 1.12.4, link to Google's CDN vs. local

### PR DESCRIPTION
**Pull request by louquillio**
Addresses version/vulnerability concerns reported elsewhere.

modified:   _layouts/default.html
modified:   _layouts/home.html

### CODE REVIEW

**Comment by x1ddos** [comment]
Should this change also remove the now-stale jQuery from https://github.com/webrtc/webrtc-org/tree/aa54885ce17525a2bdb65217e8305d5fbd4ad64b/assets/js ?

**Comment by x1ddos** [comment]
Also, related: does ajax.googleapis.com happen to host bootstrap.js as well? that way assets/js cloud be removed altogether.

**Comment by louquillio** [comment]
On Tue, Aug 30, 2016 at 2:18 PM, alex notifications@github.com wrote:

> Also, related: does ajax.googleapis.com happen to host bootstrap.js as well? that way assets/js cloud be removed altogether.

Would that it did, but no.

LQ

**Comment by louquillio** [comment]
On Tue, Aug 30, 2016 at 2:16 PM, alex notifications@github.com wrote:

> Should this change also remove the now-stale jQuery from
> https://github.com/webrtc/webrtc-org/tree/aa54885ce17525a2bdb65217e8305d5fbd4ad64b/assets/js
> ?

Indeed it should.

https://github.com/webrtc/webrtc-org/pull/90

**Comment by KaptenJansson** [comment]
LGTM

**Comment by x1ddos** [comment]
Thanks!

**Pull request merged**
