### PR TITLE
fix some urls

### PR DESCRIPTION
**Pull request by fippo**
reported in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/discuss-webrtc/WF9Bj68MCps/GMBaUyA9EgAJ
and via #240

@MirkoBonadei PTAL - if jekyll fails because of the waterfall one that *might* be the reason this doesn't get deployed

### CODE REVIEW

**Comment by MirkoBonadei** [comment]
Thanks, so if I understand correctly, https://github.com/webrtc/webrtc-org/pull/240 need to be landed before this one.

**Comment by fippo** [comment]
:crossed_fingers:

**Comment by fippo** [comment]
image
but maybe we're now ready for the 2020s ;-)

**Comment by fippo** [comment]
I think we're now safe for this decade :-)

@samdutton if you can ping https://twitter.com/aerotwist whose site 404'd and had to be removed...

**Comment by MirkoBonadei** [comment]
:)

**Review by MirkoBonadei — APPROVED** [review]

**Comment by fippo** [comment]
all fixed and deployed correctly (which took a while)

**Pull request merged**
